eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@192.168.1.111:8761/eureka/
      
server:
  port: 8763
  
spring:
  application:
    name: eshop-price-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.1.103:3306/eshop
    username: root
    password: root
  zipkin:
    base-url: http://192.168.1.111:9411